        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "inverse-primary": "#98d2c7",
                        "error-container": "#ffdad6",
                        "surface-variant": "#e1e3e1",
                        "inverse-surface": "#2e3130",
                        "on-error-container": "#93000a",
                        "tertiary-fixed-dim": "#fbb79f",
                        "secondary-fixed": "#ffdcc4",
                        "secondary": "#924c00",
                        "tertiary-container": "#673827",
                        "outline": "#707976",
                        "surface-tint": "#2f685f",
                        "primary-fixed": "#b4eee2",
                        "on-primary-container": "#84bdb2",
                        "secondary-container": "#fda053",
                        "surface-container-low": "#f2f4f2",
                        "outline-variant": "#bfc8c5",
                        "inverse-on-surface": "#f0f1ef",
                        "surface-container-high": "#e7e8e7",
                        "on-error": "#ffffff",
                        "on-secondary": "#ffffff",
                        "surface-container": "#edeeec",
                        "on-secondary-fixed-variant": "#6f3800",
                        "on-tertiary-fixed-variant": "#6a3a29",
                        "on-primary-fixed-variant": "#124f47",
                        "on-tertiary-fixed": "#341004",
                        "on-tertiary-container": "#e4a38c",
                        "primary-container": "#0e4d45",
                        "surface-dim": "#d9dad9",
                        "primary": "#00352f",
                        "on-primary-fixed": "#00201c",
                        "surface-bright": "#f8faf8",
                        "background": "#f8faf8",
                        "surface-container-highest": "#e1e3e1",
                        "secondary-fixed-dim": "#ffb77f",
                        "on-primary": "#ffffff",
                        "surface-container-lowest": "#ffffff",
                        "on-tertiary": "#ffffff",
                        "tertiary": "#4c2313",
                        "on-surface-variant": "#404946",
                        "on-secondary-container": "#6f3900",
                        "on-surface": "#191c1b",
                        "primary-fixed-dim": "#98d2c7",
                        "error": "#ba1a1a",
                        "on-secondary-fixed": "#2f1500",
                        "on-background": "#191c1b",
                        "tertiary-fixed": "#ffdbcf",
                        "surface": "#f8faf8"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "base": "8px",
                        "xs": "4px",
                        "lg": "48px",
                        "sm": "12px",
                        "md": "24px",
                        "xl": "80px",
                        "max-width": "1200px",
                        "gutter": "24px"
                    },
                    "fontFamily": {
                        "body-md": ["Inter", "sans-serif"],
                        "headline-lg-mobile": ["\"Source Serif 4\"", "serif"],
                        "headline-lg": ["\"Source Serif 4\"", "serif"],
                        "label-mono": ["JetBrains Mono", "monospace"],
                        "caption": ["Inter", "sans-serif"],
                        "headline-md": ["\"Source Serif 4\"", "serif"],
                        "body-hindi": ["Noto Sans", "sans-serif"],
                        "body-lg": ["Inter", "sans-serif"],
                        "display-lg": ["\"Source Serif 4\"", "serif"]
                    },
                    "fontSize": {
                        "body-md": ["16px", {"lineHeight": "26px", "fontWeight": "400"}],
                        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
                        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                        "label-mono": ["13px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                        "caption": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
                        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "body-hindi": ["18px", {"lineHeight": "30px", "fontWeight": "400"}],
                        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                        "display-lg": ["48px", {"lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
                    }
                }
            }
        }
