/** Tailwind config for the RTI Sahayak web/ UI layer.
 * theme.extend is merged from ALL 8 exported Stitch screens (design/stitch_rti_sahayak_ai_assistant/*),
 * not just draft_application_desktop - see design/_tailwind_config_backup.js for the
 * original single-screen block this started from. Do not rename or invent keys here -
 * if a screen needs a new token, add it to the design source first.
 *
 * Known conflicts resolved during the merge (see conversation history, not re-litigated here):
 *   - colors.background: used #f8faf8 (7/8 screens; no_results_answer_screen alone had #F7F4EE)
 *   - fontFamily.* (all 9 keys): used draft_application_desktop's form, which includes a
 *     generic fallback (e.g. ["Inter", "sans-serif"]) - the other 7 screens omit the fallback.
 */
module.exports = {
  content: ["./web/templates/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e1",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-secondary-container": "#6f3900",
        "on-primary-fixed-variant": "#124f47",
        "tertiary-fixed": "#ffdbcf",
        "on-background": "#191c1b",
        "surface-bright": "#f8faf8",
        "surface-container": "#edeeec",
        "secondary-container": "#fda053",
        "primary-container": "#0e4d45",
        "surface-tint": "#2f685f",
        "primary-fixed-dim": "#98d2c7",
        "on-tertiary-fixed-variant": "#6a3a29",
        "inverse-primary": "#98d2c7",
        "on-tertiary": "#ffffff",
        "background": "#f8faf8",
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed": "#341004",
        "surface": "#f8faf8",
        "tertiary": "#4c2313",
        "surface-container-low": "#f2f4f2",
        "on-tertiary-container": "#e4a38c",
        "error": "#ba1a1a",
        "inverse-surface": "#2e3130",
        "surface-container-high": "#e7e8e7",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-surface-variant": "#404946",
        "inverse-on-surface": "#f0f1ef",
        "tertiary-container": "#673827",
        "on-primary-container": "#84bdb2",
        "outline-variant": "#bfc8c5",
        "surface-dim": "#d9dad9",
        "primary": "#00352f",
        "secondary-fixed-dim": "#ffb77f",
        "on-secondary-fixed-variant": "#6f3800",
        "secondary-fixed": "#ffdcc4",
        "tertiary-fixed-dim": "#fbb79f",
        "on-surface": "#191c1b",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#2f1500",
        "primary-fixed": "#b4eee2",
        "secondary": "#924c00",
        "surface-container-highest": "#e1e3e1",
        "outline": "#707976",
        "custom-paper": "#F7F4EE",
        "custom-ink": "#12212E",
        "custom-amber": "#C6742A",
        "custom-border": "#E3DDD2",
        "custom-statutory": "#0E4D45",
        "rti-amber": "#C6742A",
        "rti-bg": "#F7F4EE",
        "rti-border": "#E3DDD2",
        "rti-text": "#12212E",
        "warning": "#B45309",
        "archival-border": "#E3DDD2",
        "paper-base": "#F7F4EE",
        "paper-border": "#E3DDD2",
        "paper-text": "#12212E",
        "amber-action": "#C6742A",
        "statutory-line": "#0E4D45",
        "success-tag-bg": "#E8F5E9",
        "success-tag-text": "#1E7A5A"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "12px",
        "input": "8px"
      },
      spacing: {
        "md": "24px",
        "lg": "48px",
        "base": "8px",
        "sm": "12px",
        "max-width": "1200px",
        "gutter": "24px",
        "xl": "80px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-md": ["\"Source Serif 4\"", "serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-hindi": ["Noto Sans", "sans-serif"],
        "display-lg": ["\"Source Serif 4\"", "serif"],
        "headline-lg": ["\"Source Serif 4\"", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["\"Source Serif 4\"", "serif"]
      },
      fontSize: {
        "headline-md": ["24px", {
            "lineHeight": "32px",
            "fontWeight": "600"
          }],
        "label-mono": ["13px", {
            "lineHeight": "16px",
            "letterSpacing": "0.05em",
            "fontWeight": "500"
          }],
        "body-lg": ["18px", {
            "lineHeight": "28px",
            "fontWeight": "400"
          }],
        "body-hindi": ["18px", {
            "lineHeight": "30px",
            "fontWeight": "400"
          }],
        "display-lg": ["48px", {
            "lineHeight": "60px",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }],
        "headline-lg": ["32px", {
            "lineHeight": "40px",
            "fontWeight": "600"
          }],
        "body-md": ["16px", {
            "lineHeight": "26px",
            "fontWeight": "400"
          }],
        "caption": ["14px", {
            "lineHeight": "20px",
            "fontWeight": "500"
          }],
        "headline-lg-mobile": ["28px", {
            "lineHeight": "36px",
            "fontWeight": "600"
          }]
      },
      boxShadow: {
        "ask-bar": "0 4px 20px rgba(18, 33, 46, 0.08)"
      }
    }
  },
  safelist: [
    "bg-surface-variant",
    "text-surface-variant",
    "border-surface-variant",
    "bg-on-primary",
    "text-on-primary",
    "border-on-primary",
    "bg-on-error-container",
    "text-on-error-container",
    "border-on-error-container",
    "bg-error-container",
    "text-error-container",
    "border-error-container",
    "bg-on-secondary-container",
    "text-on-secondary-container",
    "border-on-secondary-container",
    "bg-on-primary-fixed-variant",
    "text-on-primary-fixed-variant",
    "border-on-primary-fixed-variant",
    "bg-tertiary-fixed",
    "text-tertiary-fixed",
    "border-tertiary-fixed",
    "bg-on-background",
    "text-on-background",
    "border-on-background",
    "bg-surface-bright",
    "text-surface-bright",
    "border-surface-bright",
    "bg-surface-container",
    "text-surface-container",
    "border-surface-container",
    "bg-secondary-container",
    "text-secondary-container",
    "border-secondary-container",
    "bg-primary-container",
    "text-primary-container",
    "border-primary-container",
    "bg-surface-tint",
    "text-surface-tint",
    "border-surface-tint",
    "bg-primary-fixed-dim",
    "text-primary-fixed-dim",
    "border-primary-fixed-dim",
    "bg-on-tertiary-fixed-variant",
    "text-on-tertiary-fixed-variant",
    "border-on-tertiary-fixed-variant",
    "bg-inverse-primary",
    "text-inverse-primary",
    "border-inverse-primary",
    "bg-on-tertiary",
    "text-on-tertiary",
    "border-on-tertiary",
    "bg-background",
    "text-background",
    "border-background",
    "bg-on-primary-fixed",
    "text-on-primary-fixed",
    "border-on-primary-fixed",
    "bg-on-tertiary-fixed",
    "text-on-tertiary-fixed",
    "border-on-tertiary-fixed",
    "bg-surface",
    "text-surface",
    "border-surface",
    "bg-tertiary",
    "text-tertiary",
    "border-tertiary",
    "bg-surface-container-low",
    "text-surface-container-low",
    "border-surface-container-low",
    "bg-on-tertiary-container",
    "text-on-tertiary-container",
    "border-on-tertiary-container",
    "bg-error",
    "text-error",
    "border-error",
    "bg-inverse-surface",
    "text-inverse-surface",
    "border-inverse-surface",
    "bg-surface-container-high",
    "text-surface-container-high",
    "border-surface-container-high",
    "bg-surface-container-lowest",
    "text-surface-container-lowest",
    "border-surface-container-lowest",
    "bg-on-error",
    "text-on-error",
    "border-on-error",
    "bg-on-surface-variant",
    "text-on-surface-variant",
    "border-on-surface-variant",
    "bg-inverse-on-surface",
    "text-inverse-on-surface",
    "border-inverse-on-surface",
    "bg-tertiary-container",
    "text-tertiary-container",
    "border-tertiary-container",
    "bg-on-primary-container",
    "text-on-primary-container",
    "border-on-primary-container",
    "bg-outline-variant",
    "text-outline-variant",
    "border-outline-variant",
    "bg-surface-dim",
    "text-surface-dim",
    "border-surface-dim",
    "bg-primary",
    "text-primary",
    "border-primary",
    "bg-secondary-fixed-dim",
    "text-secondary-fixed-dim",
    "border-secondary-fixed-dim",
    "bg-on-secondary-fixed-variant",
    "text-on-secondary-fixed-variant",
    "border-on-secondary-fixed-variant",
    "bg-secondary-fixed",
    "text-secondary-fixed",
    "border-secondary-fixed",
    "bg-tertiary-fixed-dim",
    "text-tertiary-fixed-dim",
    "border-tertiary-fixed-dim",
    "bg-on-surface",
    "text-on-surface",
    "border-on-surface",
    "bg-on-secondary",
    "text-on-secondary",
    "border-on-secondary",
    "bg-on-secondary-fixed",
    "text-on-secondary-fixed",
    "border-on-secondary-fixed",
    "bg-primary-fixed",
    "text-primary-fixed",
    "border-primary-fixed",
    "bg-secondary",
    "text-secondary",
    "border-secondary",
    "bg-surface-container-highest",
    "text-surface-container-highest",
    "border-surface-container-highest",
    "bg-outline",
    "text-outline",
    "border-outline",
    "bg-custom-paper",
    "text-custom-paper",
    "border-custom-paper",
    "bg-custom-ink",
    "text-custom-ink",
    "border-custom-ink",
    "bg-custom-amber",
    "text-custom-amber",
    "border-custom-amber",
    "bg-custom-border",
    "text-custom-border",
    "border-custom-border",
    "bg-custom-statutory",
    "text-custom-statutory",
    "border-custom-statutory",
    "bg-rti-amber",
    "text-rti-amber",
    "border-rti-amber",
    "bg-rti-bg",
    "text-rti-bg",
    "border-rti-bg",
    "bg-rti-border",
    "text-rti-border",
    "border-rti-border",
    "bg-rti-text",
    "text-rti-text",
    "border-rti-text",
    "bg-warning",
    "text-warning",
    "border-warning",
    "bg-archival-border",
    "text-archival-border",
    "border-archival-border",
    "bg-paper-base",
    "text-paper-base",
    "border-paper-base",
    "bg-paper-border",
    "text-paper-border",
    "border-paper-border",
    "bg-paper-text",
    "text-paper-text",
    "border-paper-text",
    "bg-amber-action",
    "text-amber-action",
    "border-amber-action",
    "bg-statutory-line",
    "text-statutory-line",
    "border-statutory-line",
    "bg-success-tag-bg",
    "text-success-tag-bg",
    "border-success-tag-bg",
    "bg-success-tag-text",
    "text-success-tag-text",
    "border-success-tag-text",
    "rounded-DEFAULT",
    "rounded-t-DEFAULT",
    "rounded-r-DEFAULT",
    "rounded-b-DEFAULT",
    "rounded-l-DEFAULT",
    "rounded-lg",
    "rounded-t-lg",
    "rounded-r-lg",
    "rounded-b-lg",
    "rounded-l-lg",
    "rounded-xl",
    "rounded-t-xl",
    "rounded-r-xl",
    "rounded-b-xl",
    "rounded-l-xl",
    "rounded-full",
    "rounded-t-full",
    "rounded-r-full",
    "rounded-b-full",
    "rounded-l-full",
    "rounded-card",
    "rounded-t-card",
    "rounded-r-card",
    "rounded-b-card",
    "rounded-l-card",
    "rounded-input",
    "rounded-t-input",
    "rounded-r-input",
    "rounded-b-input",
    "rounded-l-input",
    "p-md",
    "px-md",
    "py-md",
    "pt-md",
    "pr-md",
    "pb-md",
    "pl-md",
    "m-md",
    "mx-md",
    "my-md",
    "mt-md",
    "mr-md",
    "mb-md",
    "ml-md",
    "gap-md",
    "gap-x-md",
    "gap-y-md",
    "w-md",
    "h-md",
    "max-w-md",
    "p-lg",
    "px-lg",
    "py-lg",
    "pt-lg",
    "pr-lg",
    "pb-lg",
    "pl-lg",
    "m-lg",
    "mx-lg",
    "my-lg",
    "mt-lg",
    "mr-lg",
    "mb-lg",
    "ml-lg",
    "gap-lg",
    "gap-x-lg",
    "gap-y-lg",
    "w-lg",
    "h-lg",
    "max-w-lg",
    "p-base",
    "px-base",
    "py-base",
    "pt-base",
    "pr-base",
    "pb-base",
    "pl-base",
    "m-base",
    "mx-base",
    "my-base",
    "mt-base",
    "mr-base",
    "mb-base",
    "ml-base",
    "gap-base",
    "gap-x-base",
    "gap-y-base",
    "w-base",
    "h-base",
    "max-w-base",
    "p-sm",
    "px-sm",
    "py-sm",
    "pt-sm",
    "pr-sm",
    "pb-sm",
    "pl-sm",
    "m-sm",
    "mx-sm",
    "my-sm",
    "mt-sm",
    "mr-sm",
    "mb-sm",
    "ml-sm",
    "gap-sm",
    "gap-x-sm",
    "gap-y-sm",
    "w-sm",
    "h-sm",
    "max-w-sm",
    "p-max-width",
    "px-max-width",
    "py-max-width",
    "pt-max-width",
    "pr-max-width",
    "pb-max-width",
    "pl-max-width",
    "m-max-width",
    "mx-max-width",
    "my-max-width",
    "mt-max-width",
    "mr-max-width",
    "mb-max-width",
    "ml-max-width",
    "gap-max-width",
    "gap-x-max-width",
    "gap-y-max-width",
    "w-max-width",
    "h-max-width",
    "max-w-max-width",
    "p-gutter",
    "px-gutter",
    "py-gutter",
    "pt-gutter",
    "pr-gutter",
    "pb-gutter",
    "pl-gutter",
    "m-gutter",
    "mx-gutter",
    "my-gutter",
    "mt-gutter",
    "mr-gutter",
    "mb-gutter",
    "ml-gutter",
    "gap-gutter",
    "gap-x-gutter",
    "gap-y-gutter",
    "w-gutter",
    "h-gutter",
    "max-w-gutter",
    "p-xl",
    "px-xl",
    "py-xl",
    "pt-xl",
    "pr-xl",
    "pb-xl",
    "pl-xl",
    "m-xl",
    "mx-xl",
    "my-xl",
    "mt-xl",
    "mr-xl",
    "mb-xl",
    "ml-xl",
    "gap-xl",
    "gap-x-xl",
    "gap-y-xl",
    "w-xl",
    "h-xl",
    "max-w-xl",
    "p-xs",
    "px-xs",
    "py-xs",
    "pt-xs",
    "pr-xs",
    "pb-xs",
    "pl-xs",
    "m-xs",
    "mx-xs",
    "my-xs",
    "mt-xs",
    "mr-xs",
    "mb-xs",
    "ml-xs",
    "gap-xs",
    "gap-x-xs",
    "gap-y-xs",
    "w-xs",
    "h-xs",
    "max-w-xs",
    "font-headline-md",
    "font-label-mono",
    "font-body-lg",
    "font-body-hindi",
    "font-display-lg",
    "font-headline-lg",
    "font-body-md",
    "font-caption",
    "font-headline-lg-mobile",
    "text-headline-md",
    "text-label-mono",
    "text-body-lg",
    "text-body-hindi",
    "text-display-lg",
    "text-headline-lg",
    "text-body-md",
    "text-caption",
    "text-headline-lg-mobile",
    "shadow-ask-bar"
  ],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ]
}
